title: Voeg een lichtbron toe
hero_image: images/banner.png
description: Voeg een lichtbron toe
version: 4
listed: false
copyedit: false
last_tested: "2021-12-02"
steps:
  - 
    title: Voeg een lichtbron toe
