title: Ajouter une source lumineuse
hero_image: images/banner.png
description: Ajouter une source lumineuse
version: 4
listed: false
copyedit: false
last_tested: "2021-12-02"
steps:
  - 
    title: Ajouter une source lumineuse
